### ISSUE TITLE
Cannot build due to RGB.NET.Devices.Msi (and others) missing from nuget repository

### ISSUE THREAD

**Issue by watermelonpizza** [DarthAffe/KeyboardAudioVisualizer#54]
`RGB.NET.Devices.Msi` (and other packages/versions) seems to be missing from the nuget repo, thus cannot build the project

`http://nuget.arge.be/v3/search?q=msi` returns:
```json
{
    "totalHits": 1,
    "data": [
        {
            "id": "RGB.NET.Resources.Msi",
            "version": "0.1.0",
            "description": "Resources for Msi-Devices of RGB.NET",
            "authors": ["Darth Affe"],
            "iconUrl": "http://lib.arge.be/icon_package.png",
            "licenseUrl": "https://github.com/DarthAffe/RGB.NET-Resources/master/LICENSE",
            "projectUrl": "https://github.com/DarthAffe/RGB.NET-Resources",
            "registration": "http://nuget.arge.be/v3/registration/rgb.net.resources.msi/index.json",
            "summary": "Resources for Msi-Devices of RGB.NET, a C# (.NET) library for accessing various RGB-peripherals",
            "tags": [],
            "title": "RGB.NET.Resources.Msi",
            "totalDownloads": 36,
            "versions": [
                { "@id": "http://nuget.arge.be/v3/registration/rgb.net.resources.msi/0.1.0.json", "version": "0.1.0", "downloads": 36 }
            ]
        }
    ]
}
```

**Comment by ilikebuttons** [comment]
I think I'm having the same issue. I cloned from GitHub, opened the .sln file in VS Enterprise 2017, and clicked run but I get this error:

`This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\RGB.NET.Devices.Msi.0.0.1.41\build\net45\RGB.NET.Devices.Msi.targets.	KeyboardAudioVisualizer	C:\Users\vaultboy\Desktop\KEYBOARD\KeyboardAudioVisualizer\KeyboardAudioVisualizer\KeyboardAudioVisualizer.csproj	337`

I tried to restore dependencies in the NuGet Package Manager, but I get this error:

`An error occured while trying to restore packages: Unable to find version '0.0.1.41' of package 'RGB.NET'....`

I'm not sure the proper way to build a .NET project obtained through GitHub so if you have the time to do a step-by-step guide I would be sooo grateful. I would honestly be he happy if I could just get a single LED on my Corsair Strafe RGB to turn on and off from C#, I've been searching for ages on how to do this and the production version of your app is the only thing I've found that does something with my keyboard besides the iCue software.

**Comment by azsde** [comment]
Same issue here :(

**Comment by DarthAffe** [comment]
I updated the RGB.NET references - it should work now.

**Comment by azsde** [comment]
I still have issues when I checkout this project and try to build from scratch

**Comment by DarthAffe** [comment]
There was still an old build-target left which I just removed. If it still doesn't work now I need the exact error-message.

**Comment by azsde** [comment]
Build successfull :)

Thank you for your reactivity !
